export default function repositoryTemplate(
  name,
  pluralName,
  pascalName,
  camelName,
  repoName
) {
  return `
    import { ${pascalName}RepositoryInterface } from './${camelName}Repository.interface';
    import { baseRepository } from '@domain/base/base.repository';
    import { BaseRepositoryInterface } from "@domain/base/baseRepository.interface";
    import prisma from '../../../config/db';
    import { ${pluralName} } from '@prisma/client';

    /**
     *
     * The ${pascalName}Repository is includes extra function for implementing.
     * Generated By mini-express-generator(https://www.npmjs.com/package/mini-express-generator)
     * @author Nay Ba la
     * https://github.com/naybala
     * https://naybala.netlify.app/
     * SOP @author Htin Lin Phyo
     * https://github.com/htinlinnphyo123
     * his personal portfolio is not implement yet!
     *
     */

    export const ${camelName}Repository = (): ${pascalName}RepositoryInterface => {
      const getRepo = () => baseRepository<${pluralName}>(prisma.${pluralName});
      return {
        ...getRepo(),
      };
    };
`;
}
