export default function repositoryInterfaceTemplate(
  name,
  pluralName,
  pascalName,
  camelName,
  repoName
) {
  return `import { ${pluralName} } from "@prisma/client";
import { BaseRepositoryInterface } from "@domain/base/baseRepository.interface";

/**
 *
 * The ${pascalName}RepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * SOP @author Htin Linn Phyo
 * https://github.com/htinlinnphyo123
 * https://htinlinnphyo.vercel.app/
 *
 */

export interface ${pascalName}RepositoryInterface extends BaseRepositoryInterface<${pluralName}> {
}
`;
}
