export default function repositoryInterfaceTemplate(
  name,
  pluralName,
  pascalName,
  camelName,
  repoName
) {
  return `import { ${pluralName} } from "@prisma/client";
    import { BaseRepositoryInterface } from "../base/baseRepository.interface";

    /**
     *
     * The ${pascalName}RepositoryInterface is declaration of methods inside of Repository.
     * Generated By Custom Artisan Cmd
     * @author Nay Ba la
     * https://github.com/naybala
     * https://naybala.netlify.app/
     * SOP @author Htin Lin Phyo
     * https://github.com/htinlinnphyo123
     * his personal portfolio is not implement yet!
     *
     */

    export interface ${pascalName}RepositoryInterface extends BaseRepositoryInterface<${pluralName}> {
    }
`;
}
