export default function resourceIndexTemplate(
  name,
  pluralName,
  pascalName,
  camelName,
  repoName,
  type,
  extraFields = []
) {
  const generateExtraFields = (fields) => {
    return fields
      .map((field) => `    ${field.name}: data.${field.name},`)
      .join("\n");
  };

  const extraFieldLines = generateExtraFields(extraFields);
  const typeSmallCase = type.toLowerCase();
  return `
import { PaginationResourceType } from "@${typeSmallCase}/base/types/paginate";
import { buildPaginatedResource } from "@${typeSmallCase}/base/buildPaginatedResource";
import { ${pluralName} } from "@prisma/client";

/**
 *
 * The ${pascalName}Resource is implement for sending data with requirements of desire template.
 * Generated By mini-express-generator(https://www.npmjs.com/package/mini-express-generator)
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * SOP @author Htin Linn Phyo
 * https://github.com/htinlinnphyo123
 * https://htinlinnphyo.vercel.app/
 *
 */

type Paginate${pascalName}Type = {
  data: ${pluralName}[];
} & PaginationResourceType;

const transform${pascalName} = (data: ${pluralName}) => {
  return {
    id: data.id,

  };
};

export const index${pascalName}Resource = (data: Paginate${pascalName}Type) => {
  return buildPaginatedResource(data, transform${pascalName});
};

export const getAll${pascalName} = (data: ${pluralName}[]) => {
  return data.map(transform${pascalName});
};

export const show${pascalName}Resource = (data: ${pluralName}) => ({
  ...transform${pascalName}(data),
${extraFieldLines}
});
`;
}
