export default function routeTemplate(
  name,
  pluralName,
  pascalName,
  camelName,
  repoName,
  type
) {
  const typeSmallCase = type.toLowerCase();
  return `import { Router } from "express";
import { authenticate } from "@${typeSmallCase}/base/auth";
import * as ${camelName}Controller from "@${typeSmallCase}/${pluralName}/controllers";
import { store${pascalName}Validator, update${pascalName}Validator } from "@${typeSmallCase}/${pluralName}/validations";
import { validateRequest } from "@${typeSmallCase}/base/validateRequest";

/**
 *
 * The ${pascalName}Route is implement for REST Api format GET, POST, PUT, DELETE.
 * Generated By mini-express-generator(https://www.npmjs.com/package/mini-express-generator)
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 * SOP @author Htin Linn Phyo
 * https://github.com/htinlinnphyo123
 * https://htinlinnphyo.vercel.app/
 *
 */

const router: Router = Router();
router.use(authenticate);

router.get("/", ${camelName}Controller.index);
router.get("/:id", ${camelName}Controller.show);
router.post(
  "/",
  store${pascalName}Validator,
  validateRequest,
  ${camelName}Controller.store
);
router.put(
  "/:id",
  update${pascalName}Validator,
  validateRequest,
  ${camelName}Controller.update
);
router.delete("/:id", ${camelName}Controller.destroy);

export default router;
`;
}
